"""The backend half of the shared baseline contract.

Two implementations of one contract is what produced #106, and the same shape
produced this one. The backend has computed a personal baseline, z-scores and a
deviation score since the beginning — against SQLite. Production writes to
Supabase and never called it, so what a student actually saw was

    1 + triggers * 0.8 - protective * 0.25 + relations * 0.05

computed in `app/api/entries/route.ts` from a single submission, with no history
and no baseline, rendered as "Hybrid Reflection Signal".

Both sides are now pinned to `sentra/shared/baseline_conformance.json`. The
expected values in that file were generated by running the functions tested
here, so this suite is what makes the fixture authoritative: if the backend's
arithmetic changes, this goes red and the fixture must be regenerated
deliberately rather than the two stores drifting apart in silence.
"""

import json
from datetime import date, timedelta
from pathlib import Path

import pytest

from app.analytics.aggregation import aggregate_daily_features
from app.analytics.baseline import RAMP_UP_DAYS, baseline_provenance, get_effective_baseline
from app.analytics.hybrid_inference import score_baseline_deviation
from app.analytics.scoring import compute_zscores
from app.schemas.analytics import DailyFeatureAggregation
from app.services.inference_orchestrator import MIN_REFLECTION_BASELINE_DAYS

CONTRACT_PATH = Path(__file__).resolve().parents[2] / "shared" / "baseline_conformance.json"

TOLERANCE = 1e-9


class _Extraction:
    """Stands in for an Extraction row; the aggregator reads only these two."""

    def __init__(self, nodes, relations):
        self.nodes_json = nodes
        self.relations_json = relations


@pytest.fixture(scope="module")
def contract() -> dict:
    assert CONTRACT_PATH.exists(), f"shared contract missing at {CONTRACT_PATH}"
    return json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))


def _vector(graphs: list) -> dict:
    aggregation = aggregate_daily_features(
        "fixture_user",
        date(2026, 8, 1),
        [_Extraction(graph["nodes"], graph["relations"]) for graph in graphs],
    )
    return aggregation.feature_vector_json


def _aggregations(vectors: list) -> list:
    return [
        DailyFeatureAggregation(
            user_id="fixture_user",
            day=date(2026, 7, 1) + timedelta(days=index),
            state_count=0, trigger_count=0, protective_count=0, behavior_count=0,
            event_count=0, event_avg_duration=0.0, protective_ratio=1.0,
            isolation_signal=0.0, feature_vector_json=vector,
        )
        for index, vector in enumerate(vectors)
    ]


def _evaluate(today_graphs: list, history_days: list) -> dict:
    """The orchestrator's gate, inline: history length, then baseline, then z.

    `process_day` cannot be called directly here — it needs a database session,
    entries and extractions. The three decisions under contract are these, in
    this order, and they are lifted verbatim from steps 3 and 4 of that method.
    """
    today_vector = _vector(today_graphs)
    history_vectors = [_vector(day) for day in history_days]
    observed = len(history_vectors)

    if observed < MIN_REFLECTION_BASELINE_DAYS:
        return {
            "status": "not_enough_data",
            "observed_days": observed,
            "required_days": MIN_REFLECTION_BASELINE_DAYS,
            "baseline_provenance": baseline_provenance("none", observed),
            "feature_vector": today_vector,
        }

    baseline, baseline_type = get_effective_baseline("fixture_user", _aggregations(history_vectors))
    if baseline is None:
        return {
            "status": "not_enough_data",
            "observed_days": observed,
            "required_days": MIN_REFLECTION_BASELINE_DAYS,
            "baseline_provenance": baseline_provenance("none", observed),
            "feature_vector": today_vector,
        }

    z_scores = compute_zscores(today_vector, baseline.stats_json)
    return {
        "status": "ok",
        "observed_days": observed,
        "baseline_type": baseline_type,
        "baseline_provenance": baseline_provenance(baseline_type, observed),
        "feature_vector": today_vector,
        "z_scores": z_scores,
        "deviation_score": round(score_baseline_deviation(z_scores), 3),
    }


def test_contract_is_the_shared_file(contract):
    assert contract["contract"] == "baseline"
    assert len(contract["cases"]) >= 10
    assert contract["ramp_up_days"] == RAMP_UP_DAYS
    assert contract["min_baseline_days"] == MIN_REFLECTION_BASELINE_DAYS


def test_every_case(contract):
    """Floats are compared with a tolerance.

    Python's round() is banker's rounding and JavaScript's is not. The two
    differ only on an exact half at the fourth decimal, and pinning that would
    make the contract fail for a reason nobody cares about — which is how
    contracts get deleted.
    """
    failures = []
    for case in contract["cases"]:
        actual = _evaluate(case["today"], case["history"])
        expected = case["expected"]

        if actual["status"] != expected["status"]:
            failures.append(f"{case['name']}.status: expected {expected['status']}, got {actual['status']}")
            continue
        if actual["observed_days"] != expected["observed_days"]:
            failures.append(f"{case['name']}.observed_days: expected {expected['observed_days']}, got {actual['observed_days']}")
        if actual["baseline_provenance"] != expected["baseline_provenance"]:
            failures.append(f"{case['name']}.baseline_provenance: expected {expected['baseline_provenance']}, got {actual['baseline_provenance']}")

        for feature, want in expected["feature_vector"].items():
            got = actual["feature_vector"].get(feature)
            if got is None or abs(got - want) > TOLERANCE:
                failures.append(f"{case['name']}.feature_vector.{feature}: expected {want}, got {got}")

        if expected["status"] != "ok":
            continue

        if set(actual["z_scores"]) != set(expected["z_scores"]):
            failures.append(f"{case['name']}.z_scores: feature sets differ")
        for feature, want in expected["z_scores"].items():
            got = actual["z_scores"].get(feature)
            if got is None or abs(got - want) > TOLERANCE:
                failures.append(f"{case['name']}.z_scores.{feature}: expected {want}, got {got}")
        if abs(actual["deviation_score"] - expected["deviation_score"]) > TOLERANCE:
            failures.append(
                f"{case['name']}.deviation_score: expected {expected['deviation_score']}, got {actual['deviation_score']}"
            )

    assert not failures, "backend diverges from the shared contract:\n  " + "\n  ".join(failures)


def test_the_ramp_produces_nothing(contract):
    """#91 in one assertion.

    The population baseline was deleted rather than measured, so below the ramp
    there is no reading at all. If a future change reintroduces a fallback, this
    is what goes red.
    """
    case = next(c for c in contract["cases"] if c["name"] == "cold_start_day_one")
    for days in range(MIN_REFLECTION_BASELINE_DAYS):
        history = [case["today"] for _ in range(days)]
        outcome = _evaluate(case["today"], history)
        assert outcome["status"] == "not_enough_data", f"{days} days must not produce a reading"
    assert get_effective_baseline("fixture_user", []) == (None, "none")


def test_the_boundary_is_exactly_fourteen(contract):
    case = next(c for c in contract["cases"] if c["name"] == "cold_start_day_one")
    thirteen = [case["today"] for _ in range(RAMP_UP_DAYS - 1)]
    assert _evaluate(case["today"], thirteen)["status"] == "not_enough_data"
    assert _evaluate(case["today"], thirteen + [case["today"]])["status"] == "ok"


def test_the_requirement_cannot_be_lowered():
    """`MIN_REFLECTION_BASELINE_DAYS` is floored at `RAMP_UP_DAYS`.

    The environment variable can raise how much history a reading rests on. It
    cannot lower it, because there is no longer anything to fill the gap with.
    """
    assert MIN_REFLECTION_BASELINE_DAYS >= RAMP_UP_DAYS


def test_an_unchanged_day_deviates_by_nothing(contract):
    """The defect on the production side, stated as the backend's behaviour.

    The route handler's formula has a floor of 1.0, so a day identical to every
    other day still read as a signal. Here it is zero.
    """
    case = next(c for c in contract["cases"] if c["name"] == "an_ordinary_day_deviates_by_little")
    assert _evaluate(case["today"], case["history"])["deviation_score"] == 0.0


def test_japanese_and_english_score_identically(contract):
    """Category counting is script-independent, and stays so.

    A contract exercised only in English would not have caught the tokenisation
    (#105) or node-identity (#107) defects this codebase has already shipped.
    """
    japanese = next(c for c in contract["cases"] if c["name"] == "japanese_entries_score_identically")
    english = next(c for c in contract["cases"] if c["name"] == "an_ordinary_day_deviates_by_little")
    assert _evaluate(japanese["today"], japanese["history"])["z_scores"] == pytest.approx(
        _evaluate(english["today"], english["history"])["z_scores"]
    )


def test_event_duration_cannot_vary_on_the_production_path(contract):
    """The production extraction schema never asks for a node duration.

    So `event_avg_duration` is zero on every production day while carrying
    weight 0.08 in the deviation table. The backend's own schema does ask for
    it, which is why this is a property of the path and not of the feature — and
    why the port reports it as degenerate rather than letting a permanently-zero
    z-score sit in a stored map looking measured (cf. #85).
    """
    case = next(c for c in contract["cases"] if c["name"] == "event_duration_never_varies_on_the_production_path")
    outcome = _evaluate(case["today"], case["history"])
    assert outcome["feature_vector"]["event_avg_duration"] == 0.0

    with_duration = _vector([{
        "nodes": [{"id": "walk", "category": "Event", "label": "walk", "intensity": 0.5, "confidence": 0.8, "duration": 30}],
        "relations": [],
    }])
    assert with_duration["event_avg_duration"] == 30.0
